workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_OPEN_MERGE_REQUESTS
      when: always


stages:
  - validate
  - build
  - test

validate-job:
  stage: validate
  when: manual
  script:
    - git clone https://$TOKEN_NAME:$ACCESS_TOKEN@gitlab.com/cpp_ivt_2022/courserepo.git ../orig_repo
    - if sh -c "diff -qr ../$CI_PROJECT_NAME/ ../orig_repo/ -x '*git*'  | grep -E 'test[^/]*\.cpp|gitlab-ci\.yml'"; then exit 1; fi


build-job:
  stage: build
  needs:
    - validate-job
  script:
    - echo "Try to run CMake build"
    - cmake -B build_directory
    - cmake --build build_directory --target $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  artifacts:
    paths:
      - build_directory/


test-job:
  stage: test
  dependencies:
    - build-job
  needs:
    - build-job
  script:
    - ./build_directory/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -v normal

